import { Product } from '@/domain/catalog/types'

export const mockRecommended: Product[] = [
  {
    id: 'r1',
    title: 'Tênis Nike Air Max 270 Masculino',
    price: 549.9,
    installments: '6x R$ 91,65 sem juros',
    freeShipping: true,
    rating: 4.6,
    reviewCount: 1234,
    icon: 'ti-shoe',
  },
  {
    id: 'r2',
    title: 'Aspirador de Pó Robô Inteligente Wi-Fi',
    price: 899.0,
    installments: '10x R$ 89,90 sem juros',
    freeShipping: true,
    rating: 4.5,
    reviewCount: 678,
    icon: 'ti-ironing',
    badge: 'OFERTA',
  },
  {
    id: 'r3',
    title: 'Câmera Sony Alpha ZV-E10 Kit 16-50mm',
    price: 4199.0,
    installments: '12x R$ 349,91 sem juros',
    freeShipping: true,
    rating: 4.9,
    reviewCount: 312,
    icon: 'ti-camera',
    badge: 'NOVO',
  },
  {
    id: 'r4',
    title: 'Bicicleta Elétrica Dobrável 350W Urbana',
    price: 3499.0,
    installments: '12x R$ 291,58 sem juros',
    freeShipping: true,
    rating: 4.7,
    reviewCount: 203,
    icon: 'ti-bike',
  },
]
